CXXFLAGS += -std=c++11

#CXXFLAGS += -DHIERARCHICAL_BLOCKS
#SRCS += $(foreach s, $(wildcard ../src/hier/*.cpp), $(shell basename $(s)))

SRCS += $(foreach s, $(wildcard ../src/basic/*.cpp), $(shell basename $(s)))

include ../../common/systemc.mk
