#ifndef __SYNTH_CFG_H__
#define __SYNTH_CFG_H__

#include "libesp.h"

#define NACC 12
esp_thread_info_t cfg_synth[][1] = {
    {
        {
		.run = true,
		.devname = "synth.0",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	    }
    },
	{{
		.run = true,
		.devname = "synth.1",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.2",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.3",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.4",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.5",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.6",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.7",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.8",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.9",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.10",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}},
    {{
		.run = true,
		.devname = "synth.11",
		.type = synth,
		/* <<--descriptor-->> */
        .desc.synth_desc.offset = 0,
		.desc.synth_desc.pattern = 0,
		.desc.synth_desc.in_size = 0,
		.desc.synth_desc.access_factor = 0,
		.desc.synth_desc.burst_len = 0,
		.desc.synth_desc.compute_bound_factor = 0,
		.desc.synth_desc.irregular_seed = 0,
		.desc.synth_desc.reuse_factor = 0,
		.desc.synth_desc.ld_st_ratio = 0,
		.desc.synth_desc.stride_len = 0,
		.desc.synth_desc.out_size = 0,
		.desc.synth_desc.in_place = 0,
		.desc.synth_desc.wr_data = 0,
		.desc.synth_desc.src_offset = 0,
		.desc.synth_desc.dst_offset = 0,
		.desc.synth_desc.esp.coherence = ACC_COH_NONE,
		.desc.synth_desc.esp.p2p_store = 0,
		.desc.synth_desc.esp.p2p_nsrcs = 0,
		.desc.synth_desc.esp.p2p_srcs = {"", "", "", ""},
	}}
};
#endif /* __SYNTH_CFG_H__ */
